# Generated by Django 5.1.4 on 2025-02-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authify', '0003_blacklist_unique_block_entry_alter_blacklist_table'),
        ('profile', '0006_rename_user_clerbie_friends_user1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerbie',
            name='about_me',
            field=models.TextField(blank=True, max_length=50000, null=True),
        ),
        migrations.AddField(
            model_name='clerbie',
            name='technologies',
            field=models.ManyToManyField(blank=True, related_name='user_techonlogies', to='profile.technologies'),
        ),
    ]
