# Generated by Django 5.1.4 on 2025-02-20 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authify', '0004_clerbie_about_me_clerbie_technologies'),
        ('profile', '0020_jobtitles'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerbie',
            name='job_title',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.jobtitles'),
        ),
    ]
