# Generated by Django 5.1.2 on 2024-11-09 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_actived',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='is_authenticated',
            field=models.BooleanField(default=False),
        ),
    ]
