# Generated by Django 5.1.2 on 2024-11-14 17:30

import blog_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0002_bloguser_is_actived_bloguser_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=blog_user.models.image_upload_function),
        ),
    ]
