# Generated by Django 5.1.2 on 2024-11-19 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0004_remove_bloguser_is_admin_bloguser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='is_authenticated',
        ),
    ]
