# Generated by Django 5.1.2 on 2024-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0005_remove_bloguser_is_authenticated'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
