# Generated by Django 5.1.4 on 2025-01-01 14:21

import blog_user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0006_bloguser_is_blocked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='avatar',
            field=models.ImageField(blank=True, default='default/default_avatar.png', null=True, upload_to=blog_user.models.image_upload_function),
        ),
    ]
