# Generated by Django 5.1.4 on 2025-01-07 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0011_certificates_education_hobby_technologies_work_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='work',
            table='Works',
        ),
    ]
