# Generated by Django 5.1.4 on 2025-01-14 19:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_user', '0013_remove_bloguser_friends_unique_friendship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_project', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
