# Generated by Django 5.1.4 on 2025-01-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='invitation',
            name='offer_type',
            field=models.CharField(choices=[('request', 'Request'), ('invite', 'Invite')], default='request', max_length=7),
        ),
    ]
