# Generated by Django 5.1.4 on 2025-01-30 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0002_clerbie_hobbies_newfield'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerbie_hobbies',
            old_name='created_at',
            new_name='created_timestamp',
        ),
        migrations.RemoveField(
            model_name='clerbie_hobbies',
            name='newfield',
        ),
    ]
