# Generated by Django 5.1.4 on 2025-01-30 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_rename_created_at_clerbie_hobbies_created_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerbie_hobbies',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
