# Generated by Django 5.1.4 on 2025-01-17 19:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0003_remove_inboxmessage_invitation_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inboxmessage',
            name='offer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile.offers'),
        ),
    ]
