# Generated by Django 5.1.4 on 2025-01-30 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_clerbie_hobbies_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerbie_hobbies',
            name='created_timestamp',
        ),
    ]
