# Generated by Django 5.1.4 on 2025-01-22 17:12

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0004_alter_inboxmessage_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerbie_friends',
            name='offer_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
