# Generated by Django 5.1.4 on 2025-01-22 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0005_clerbie_friends_offer_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerbie_friends',
            name='expires_at',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
