# Generated by Django 5.1.4 on 2025-02-11 15:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0006_rename_user_clerbie_friends_user1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerbie_education',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='clerbie_education',
            name='description',
        ),
        migrations.RemoveField(
            model_name='clerbie_education',
            name='education',
        ),
        migrations.AddField(
            model_name='clerbie_education',
            name='ended_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='clerbie_education',
            name='specialty',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='clerbie_education',
            name='started_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clerbie_education',
            name='university',
            field=models.ForeignKey(max_length=50, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='universities', to='profile.education'),
        ),
        migrations.AddField(
            model_name='education',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='clerbie_education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL),
        ),
    ]
