# Generated by Django 5.1.4 on 2025-01-22 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0007_clerbie_friends_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerbie_friends',
            old_name='added_at',
            new_name='created_at',
        ),
    ]
