# Generated by Django 5.1.4 on 2025-02-12 16:21

import django.db.models.deletion
import profile.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0008_rename_education_university'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clerbie_certificates',
            name='certificates',
        ),
        migrations.RemoveField(
            model_name='clerbie_certificates',
            name='created_at',
        ),
        migrations.AddField(
            model_name='clerbie_certificates',
            name='issued_at',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='clerbie_certificates',
            name='organization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='clerbie_certificates',
            name='photo',
            field=models.ImageField(null=True, upload_to=profile.models.image_upload_certification_function),
        ),
        migrations.AddField(
            model_name='clerbie_certificates',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clerbie_certificates',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
        migrations.AlterField(
            model_name='clerbie_certificates',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='clerbie_education',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Certificates',
        ),
    ]
