# Generated by Django 5.1.4 on 2025-02-12 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0009_remove_clerbie_certificates_certificates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerbie_certificates',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
