# Generated by Django 5.1.4 on 2025-02-13 08:07

import django.db.models.deletion
import profile.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0010_alter_clerbie_certificates_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('photo', models.ImageField(default='default/default_company_logo.png', upload_to=profile.models.image_upload_function)),
                ('description', models.TextField(blank=True, max_length=7000, null=True)),
            ],
            options={
                'db_table': 'Companies',
            },
        ),
        migrations.RemoveField(
            model_name='clerbie_hobbies',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='clerbie_hobbies',
            name='user',
        ),
        migrations.RemoveField(
            model_name='userworkexperience',
            name='work',
        ),
        migrations.RenameField(
            model_name='userworkexperience',
            old_name='end_date',
            new_name='ended_at',
        ),
        migrations.RemoveField(
            model_name='userworkexperience',
            name='start_date',
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='position',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='started_at',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userworkexperience',
            name='description',
            field=models.TextField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='userworkexperience',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='userworkexperience',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_work', to='profile.companies'),
        ),
        migrations.DeleteModel(
            name='Hobby',
        ),
        migrations.DeleteModel(
            name='Clerbie_hobbies',
        ),
        migrations.DeleteModel(
            name='Work',
        ),
    ]
