# Generated by Django 5.1.4 on 2025-02-13 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0011_companies_remove_clerbie_hobbies_hobby_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companies',
            table='Companies',
        ),
    ]
