# Generated by Django 5.1.4 on 2025-02-13 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0013_rename_userworkexperience_userjobexperience'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='title',
            new_name='name',
        ),
    ]
