# Generated by Django 5.1.4 on 2025-02-18 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0014_rename_title_companies_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Clerbie_reactions',
            new_name='Clerbie_reviews',
        ),
        migrations.AlterModelTable(
            name='clerbie_reviews',
            table='UserReviews',
        ),
    ]
