# Generated by Django 5.1.4 on 2025-02-18 15:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0015_rename_clerbie_reactions_clerbie_reviews_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clerbie_reviews',
            name='job_experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.userjobexperience'),
        ),
        migrations.AddField(
            model_name='clerbie_reviews',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.projects'),
        ),
        migrations.AddField(
            model_name='clerbie_reviews',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.university'),
        ),
    ]
