# Generated by Django 5.1.4 on 2025-02-18 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0016_clerbie_reviews_job_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clerbie_reviews',
            old_name='job_experience',
            new_name='job',
        ),
    ]
