# Generated by Django 5.1.4 on 2025-02-18 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile', '0018_rename_job_clerbie_reviews_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clerbie_reviews',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='profile.companies'),
        ),
    ]
