# Generated by Django 5.1.4 on 2025-02-20 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamup', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='announcement',
            table='Announcement',
        ),
    ]
