# Generated by Django 5.1.4 on 2025-03-06 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamup', '0003_announcementrequests'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementrequests',
            old_name='role',
            new_name='job_title',
        ),
    ]
