# Generated by Django 5.1.4 on 2025-03-06 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamup', '0004_rename_role_announcementrequests_job_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcementrequests',
            old_name='cv_description',
            new_name='cover_list',
        ),
    ]
