# Generated by Django 5.1.4 on 2025-03-06 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teamup', '0005_rename_cv_description_announcementrequests_cover_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcementrequests',
            name='status',
        ),
    ]
