# Generated by Django 5.1.2 on 2024-11-20 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_postreactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='postreactions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postreactions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
