# Generated by Django 5.1.2 on 2024-11-21 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_postreactions_created_at_postreactions_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
