# Generated by Django 5.1.4 on 2024-12-16 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_chatroom_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('delivered', 'Delivered'), ('read', 'Read')], default='delivered', max_length=10),
        ),
    ]
