# Generated by Django 5.1.4 on 2025-01-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0009_message_reply_from'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='chatroom',
            table='Chats',
        ),
        migrations.AlterModelTable(
            name='commentreactions',
            table='CommentReactions',
        ),
        migrations.AlterModelTable(
            name='comments',
            table='PostComments',
        ),
        migrations.AlterModelTable(
            name='message',
            table='ChatMessages',
        ),
        migrations.AlterModelTable(
            name='postreactions',
            table='PostReactions',
        ),
        migrations.AlterModelTable(
            name='posts',
            table='Posts',
        ),
    ]
